# Generated by Django 2.0.6 on 2018-06-26 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinfo',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='heroinfo',
            options={'ordering': ['id']},
        ),
        migrations.RenameField(
            model_name='heroinfo',
            old_name='hBook',
            new_name='hbook',
        ),
        migrations.AddField(
            model_name='bookinfo',
            name='bcommnet',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bookinfo',
            name='bread',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bookinfo',
            name='isDelete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='heroinfo',
            name='isDelete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='heroinfo',
            name='hgender',
            field=models.BooleanField(default=True),
        ),
    ]
