# Generated by Django 2.0.6 on 2018-06-27 11:17

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0003_auto_20180626_1752'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaInfo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('areaid', models.CharField(max_length=10)),
                ('area', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'areas',
            },
        ),
        migrations.CreateModel(
            name='CityInfo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('cityid', models.CharField(max_length=10, unique=True)),
                ('city', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'cities',
            },
        ),
        migrations.CreateModel(
            name='ProvInfo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('provinceid', models.CharField(max_length=10, unique=True)),
                ('province', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'provinces',
            },
        ),
        migrations.AlterModelManagers(
            name='heroinfo',
            managers=[
                ('heros', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='cityinfo',
            name='province',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='booktest.ProvInfo', to_field='provinceid'),
        ),
        migrations.AddField(
            model_name='areainfo',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='booktest.CityInfo', to_field='cityid'),
        ),
    ]
